export const ARTICLES_LIST_REQUEST = "ARTICLES_LIST_REQUEST";
export const ARTICLES_LIST_SUCCESS = "ARTICLES_LIST_SUCCESS";
export const ARTICLES_LIST_FAIL = "ARTICLES_LIST_FAIL";

export const ARTICLES_CREATE_REQUEST = "ARTICLES_CREATE_REQUEST";
export const ARTICLES_CREATE_SUCCESS = "ARTICLES_CREATE_SUCCESS";
export const ARTICLES_CREATE_FAIL = "ARTICLES_CREATE_FAIL";

export const ARTICLES_UPDATE_REQUEST = "ARTICLES_UPDATE_REQUEST";
export const ARTICLES_UPDATE_SUCCESS = "ARTICLES_UPDATE_SUCCESS";
export const ARTICLES_UPDATE_FAIL = "ARTICLES_UPDATE_FAIL";

export const ARTICLES_DELETE_REQUEST = "ARTICLES_DELETE_REQUEST";
export const ARTICLES_DELETE_SUCCESS = "ARTICLES_DELETE_SUCCESS";
export const ARTICLES_DELETE_FAIL = "ARTICLES_DELETE_FAIL";

export const DISPLAY_ARTICLE_REQUEST = "DISPLAY_ARTICLE_REQUEST";
export const DISPLAY_ARTICLE_SUCCESS = "DISPLAY_ARTICLE_SUCCESS";
export const DISPLAY_ARTICLE_FAIL = "DISPLAY_ARTICLE_FAIL";

export const ARTICLES_DISPLAY_REQUEST = "ARTICLES_DISPLAY_REQUEST";
export const ARTICLES_DISPLAY_SUCCESS = "ARTICLES_DISPLAY_SUCCESS";
export const ARTICLES_DISPLAY_FAIL = "ARTICLES_DISPLAY_FAIL";

export const ARTICLES_LIKE_REQUEST = "ARTICLES_LIKE_REQUEST";
export const ARTICLES_LIKE_SUCCESS = "ARTICLES_LIKE_SUCCESS";
export const ARTICLES_LIKE_FAIL = "ARTICLES_LIKE_FAIL";

export const ARTICLES_COMMENT_REQUEST = "ARTICLES_COMMENT_REQUEST";
export const ARTICLES_COMMENT_SUCCESS = "ARTICLES_COMMENT_SUCCESS";
export const ARTICLES_COMMENT_FAIL = "ARTICLES_COMMENT_FAIL";
